FROM docker.io/library/ubuntu:23.04

RUN apt-get -y update \
    && apt-get -y install openssl python3-lz4 python3-protobuf python3-strictyaml \
    && find /var/cache/apt/archives /var/lib/apt/lists -mindepth 1 -delete
