# Metadata used when generating OTAs. These values don't affect behavior at all.
[ota_info]
# Make sure generated OTAs aren't flashable on real devices.
device = "avbroot_fake_device"
fingerprint = "avbroot/avbroot_fake_device:14/UQ1A.240101.000/12345678:user/release-keys"
build_number = "UQ1A.240101.000"
incremental_version = "12345678"
android_version = "14"
sdk_version = "34"
security_patch_level = "2024-01-01"

# Fake test device for ML-DSA signing.

[profile.ml_dsa_test]
avb_key_type = "ml_dsa"

[profile.ml_dsa_test.partitions.boot]
avb.signed = true
data.type = "boot"
data.version = "v4"
data.kernel = true
data.ramdisks = [["init", "otacerts", "first_stage", "dsu_key_dir"]]

[profile.ml_dsa_test.partitions.system]
avb.signed = false
data.type = "dm_verity"
data.content = "system_otacerts"

[profile.ml_dsa_test.partitions.vbmeta]
avb.signed = true
data.type = "vbmeta"
data.deps = ["boot", "system"]

[profile.ml_dsa_test.hashes_streaming]
original = "15722553615f46a197efcdf8545b6317425d18b4fc1a815a2f422a3b9ba55f35"
patched = "9972df9a958e971831308111b1023a40e7a431eddd95b68f61b342ba2b69a5e4"

[profile.ml_dsa_test.hashes_seekable]
original = "f43cb8369d36c8fc9cef2161a5f5860eb922feaab8ad597afee875b5758ff30d"
patched = "cd2ebe971b1cce8dc8dea2de097bfaf2cbfd75d6f7d7b9b8bd5eee443bf783f9"

# Google Pixel 7 Pro
# What's unique: init_boot (boot v4) + vendor_boot (vendor v4)

[profile.pixel_v4_gki]
avb_key_type = "rsa"

[profile.pixel_v4_gki.vabc]
# CoW v3 is used starting with the Google Pixel 9a.
version = { V3 = { compression_factor = 65536 } }
algo = { kind = "Lz4" }
force_compression_factor = false

[profile.pixel_v4_gki.partitions.boot]
avb.signed = true
data.type = "boot"
data.version = "v4"
data.kernel = true

[profile.pixel_v4_gki.partitions.init_boot]
avb.signed = true
data.type = "boot"
data.version = "v4"
data.ramdisks = [["init", "first_stage"]]

[profile.pixel_v4_gki.partitions.system]
avb.signed = false
data.type = "dm_verity"
data.content = "system_otacerts"

[profile.pixel_v4_gki.partitions.vbmeta]
avb.signed = true
data.type = "vbmeta"
data.deps = ["boot", "init_boot", "vendor_boot", "vbmeta_system"]

[profile.pixel_v4_gki.partitions.vbmeta_system]
avb.signed = true
data.type = "vbmeta"
data.deps = ["system"]

[profile.pixel_v4_gki.partitions.vendor_boot]
avb.signed = false
data.type = "boot"
data.version = "vendor_v4"
data.ramdisks = [["otacerts", "first_stage", "dsu_key_dir"]]

[profile.pixel_v4_gki.hashes_streaming]
original = "7dd428385b1ceadd3246f360ba674234bc5412da73a2f0667fed8d7a11f8d87b"
patched = "c28a7f052569199ae23a89459563604a3cb0da26ad85088d87df0b1198c2d3ad"

[profile.pixel_v4_gki.hashes_seekable]
original = "67de7a7992c8bba9af4467133923a67175b79302a6787a0b5b2ccf48bcf327af"
patched = "77a17bc3bdbfb892ee2757eab044c4ef93b55aefdbefbcb1dc4c133197213cca"

# Google Pixel 6a
# What's unique: boot (boot v4, no ramdisk) + vendor_boot (vendor v4, 2 ramdisks)

[profile.pixel_v4_non_gki]
avb_key_type = "rsa"

[profile.pixel_v4_non_gki.vabc]
version = "V2"
algo = { kind = "Lz4" }
# delta_generator sets it for v2, even though it's not used.
force_compression_factor = true

[profile.pixel_v4_non_gki.partitions.boot]
avb.signed = true
data.type = "boot"
data.version = "v4"
data.kernel = true

[profile.pixel_v4_non_gki.partitions.system]
avb.signed = false
data.type = "dm_verity"
data.content = "system_otacerts"

[profile.pixel_v4_non_gki.partitions.vbmeta]
avb.signed = true
data.type = "vbmeta"
data.deps = ["boot", "vendor_boot", "vbmeta_system"]

[profile.pixel_v4_non_gki.partitions.vbmeta_system]
avb.signed = true
data.type = "vbmeta"
data.deps = ["system"]

[profile.pixel_v4_non_gki.partitions.vendor_boot]
avb.signed = false
data.type = "boot"
data.version = "vendor_v4"
data.ramdisks = [["init", "otacerts", "first_stage", "dsu_key_dir"], ["dlkm"]]

[profile.pixel_v4_non_gki.hashes_streaming]
original = "c364bf151386d4e29801ad26dfd8fe90c0dd3b3175169d3c24ad01a5dca4256f"
patched = "b870a0f5bfc8b94f7b98a9eefebe856880319a043979aa109c8e8d8aa466a4cb"

[profile.pixel_v4_non_gki.hashes_seekable]
original = "86712e2eefaf3e2c515d06dbbc71b2460f62077b0047fb113ce99d801028b466"
patched = "024bd728319fd1c773758228f61a10b823b803abc1a449b40eea24a4c7d27453"

# Google Pixel 4a 5G
# What's unique: boot (boot v3) + vendor_boot (vendor v3)

[profile.pixel_v3]
avb_key_type = "rsa"

[profile.pixel_v3.vabc]
version = "V2"
algo = { kind = "Gz" }
force_compression_factor = false

[profile.pixel_v3.partitions.boot]
avb.signed = true
data.type = "boot"
data.version = "v3"
data.kernel = true
data.ramdisks = [["init"]]

[profile.pixel_v3.partitions.system]
avb.signed = false
data.type = "dm_verity"
data.content = "system_otacerts"

[profile.pixel_v3.partitions.vbmeta]
avb.signed = true
data.type = "vbmeta"
data.deps = ["boot", "vendor_boot", "vbmeta_system"]

[profile.pixel_v3.partitions.vbmeta_system]
avb.signed = true
data.type = "vbmeta"
data.deps = ["system"]

[profile.pixel_v3.partitions.vendor_boot]
avb.signed = false
data.type = "boot"
data.version = "vendor_v3"
data.ramdisks = [["otacerts", "first_stage", "dsu_key_dir"]]

[profile.pixel_v3.hashes_streaming]
original = "91d705060257f24f45b8a1dc3e38fd04b228482f8eaaba4969aa99fa3cd40289"
patched = "6957f9438e30d7b428d9d97fc43e8a5e41610f07148f27126a5f33333a8766b3"

[profile.pixel_v3.hashes_seekable]
original = "7ee0113fcf769bf522b960fc3dbb605122e73144246d0ce62c5d95933b49ba12"
patched = "8e0d4c8452900f4eedf53e301b37070fbdfe5fc8b87e3fcf122cf2c916935005"

# Google Pixel 4a
# What's unique: boot (boot v2)

[profile.pixel_v2]
avb_key_type = "rsa"

[profile.pixel_v2.partitions.boot]
avb.signed = false
data.type = "boot"
data.version = "v2"
data.kernel = true
data.ramdisks = [["init", "otacerts", "first_stage", "dsu_key_dir"]]

[profile.pixel_v2.partitions.system]
avb.signed = false
data.type = "dm_verity"
data.content = "system_otacerts"

[profile.pixel_v2.partitions.vbmeta]
avb.signed = true
data.type = "vbmeta"
data.deps = ["boot", "vbmeta_system"]

[profile.pixel_v2.partitions.vbmeta_system]
avb.signed = true
data.type = "vbmeta"
data.deps = ["system"]

[profile.pixel_v2.hashes_streaming]
original = "eef2fd21cb50e7608ba1b81aceee415d4caeb52656236d664b740a9d38094e20"
patched = "e64b20f0bc2479600d3610f88022cb02b1d51a7cb7c2436df3dde2feb3ee537d"

[profile.pixel_v2.hashes_seekable]
original = "86c11eceb0f50acd29a7ea065367d1380ed78c59a9d0674fde3115fb16b9a8f1"
patched = "821af5e44cf3ab04106d40cd7f4a52a137be9bc68ad17bddf95da9c9ca444f0f"
